# Generated by Django 3.0.8 on 2020-08-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attributes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Type fields',
                'ordering': ('type_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Id', models.CharField(max_length=126, verbose_name='Book_ID')),
                ('etag', models.CharField(max_length=126, verbose_name='etag')),
                ('selfLink', models.TextField(verbose_name='selflink')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('book_Id',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value_str', models.TextField(blank=True, null=True)),
                ('attribute_value_int', models.IntegerField(blank=True, null=True)),
                ('attribute_value_bool', models.BooleanField(blank=True, null=True)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Attribute')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
            options={
                'verbose_name_plural': 'Attributes value',
                'ordering': ('book_id',),
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='type_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.AttributeType'),
        ),
    ]
