# Generated by Django 3.0.8 on 2020-08-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='attribute_value_flout',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
