# Generated by Django 3.0.8 on 2020-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
