# Generated by Django 3.0.8 on 2020-08-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_attributevalue_attribute_value_flout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='attribute_value_flout',
            new_name='attribute_value_float',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute_value_int',
        ),
    ]
