# Generated by Django 3.0.8 on 2020-08-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200801_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('author',), 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',), 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name_plural': 'Kategorie'},
        ),
    ]
