# Generated by Django 3.0.8 on 2020-08-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200805_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('book_id', 'attribute_id'), 'verbose_name_plural': 'Attributes value'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='parent_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Attribute'),
        ),
    ]
