# Generated by Django 3.0.8 on 2020-08-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200805_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('bookId', 'attributeId'), 'verbose_name_plural': 'Attributes value'},
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='attribute_id',
            new_name='attributeId',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='book_id',
            new_name='bookId',
        ),
    ]
