# Generated by Django 3.0.8 on 2020-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200806_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_Id',
            field=models.CharField(max_length=126, verbose_name='book_ID'),
        ),
    ]
