# Generated by Django 3.0.8 on 2020-08-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_attributevalue_attribute_value_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
