# Generated by Django 3.0.8 on 2020-08-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='attribute_value_dict',
            new_name='attribute_value_list',
        ),
    ]
