# Generated by Django 3.0.8 on 2020-08-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200807_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=512, verbose_name='Author')),
            ],
            options={
                'verbose_name_plural': 'Autorzy',
                'ordering': ('author',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publishedDate',
            field=models.IntegerField(blank=True, null=True, verbose_name='publishedDate'),
        ),
    ]
