# Generated by Django 3.0.8 on 2020-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='publishedDate'),
        ),
    ]
