# Generated by Django 3.0.8 on 2020-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200807_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('author',)},
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute_value_dict',
            field=models.TextField(blank=True, null=True),
        ),
    ]
