# Generated by Django 3.0.8 on 2020-08-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200807_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=512, verbose_name='Category')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='averageRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratingsCount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attributeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Attribute'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='books.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.Category'),
        ),
    ]
