# Generated by Django 3.0.8 on 2020-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200808_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='publishedDate'),
        ),
    ]
